### ISSUE TITLE
Where to merge this tool into

### ISSUE THREAD

**Issue by BryceStevenWilley** [jhleex/SDT#1]
I came across an actual use case for this today (determining if an appeals docket number is a single justice or panel case), and will definitely be running into more use cases for it in the future. Any chance we can get this polished and merged into one of the AL repos? IDK if ALMassachusetts, or MACourts, or AssembleLine (core) is the best choice. Any suggestions or ideas, @nonprofittechy  or @plocket?

**Comment by nonprofittechy** [comment]
Macourts sounds good

**Comment by BryceStevenWilley** [comment]
This has been merged. I'm gonna close this issue, and archive this repo.
